---
title: "Mini Simulation"
author: "Megan Grieco"
date: "2023-06-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(gWQS)
library(ggplot2)
library(plotROC)
library(tidyverse)

library(bkmr)
library(bkmrhat)
library(coda)

library(corrplot)

#Imputation packages
library(Amelia)
library(mice)
library(missMDA)
library(missForest)
library(missRanger)
library(VIM)
library(softImpute)
```

```{r}
#set seed
set.seed(1111)
x <- do.call(cbind, lapply(1:10, function(i) {
    rlnorm(100, meanlog = 0, sdlog = 1)
})) %>% as.data.frame()
names(x) <- gsub(x=names(x),pattern="V",replacement="x")

y <- rnorm(100,mean = 0,sd=1)

df <- as.data.frame(cbind(y,x))

#test to make sure exposures are correlated
M = cor(df)
corrplot(M, method = 'number') # colorful number
```


```{r}
#BKMR for all observations
y <- df$y
Z <- x

set.seed(111)

#varsel = T: perform variable selection
fitkm <- kmbayes(y = y, Z = Z, iter = 10000, verbose = FALSE, varsel = TRUE)

#Estimated posterior inclusion probabilities
ExtractPIPs(fitkm) %>% arrange(-PIP)

```

```{r}
# Plot the predictor-response function
pred.resp.univar <- PredictorResponseUnivar(fit = fitkm)

ggplot(pred.resp.univar, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + 
    geom_smooth(stat = "identity") + 
    facet_wrap(~ variable) +
  ylab("h(z)")

#overall risk profile - compare changed exposure levels to median values
risks.overall <- OverallRiskSummaries(fit = fitkm, y = y, Z = Z,  
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
risks.overall

ggplot(risks.overall, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange()
```



```{r}
#WQS for all observations
# we save the names of the mixture variables in the variable "Xs"
Xs <- names(x)

set.seed(111)
# we run the model and save the results in the variable "results"
results <- gwqs(y ~ wqs, mix_name = Xs, data = df, 
                q = 10, validation = 0.6, b = 2, b1_pos = F, 
                b1_constr = FALSE, family = "gaussian", seed = 2016)
# bar plot
gwqs_barplot(results)
# scatter plot y vs wqs
gwqs_scatterplot(results)
# scatter plot residuals vs fitted values
gwqs_fitted_vs_resid(results)
```


```{r}
#randomly drop 10% of observations
set.seed(1111)
x_incomplete <- df %>% select(-y) %>%
  lapply(., function(x){replace(x, sample(length(x), .1*length(x)), NA)}) %>% as.data.frame()

df_incomplete <- cbind(y,x_incomplete)

df_incomplete_drop <- df_incomplete[complete.cases(df_incomplete), ]
```

```{r}
#BKMR excluding missing

y_missing <- df_incomplete_drop$y
Z_missing <- df_incomplete_drop[,2:11]

set.seed(111)

#varsel = T: perform variable selection
fitkm_missing <- kmbayes(y = y_missing, Z = Z_missing, iter = 10000, verbose = FALSE, varsel = TRUE)

#Estimated posterior inclusion probabilities
ExtractPIPs(fitkm_missing) %>% arrange(-PIP)

```

```{r}
#WQS excluding missing

set.seed(111)
# we run the model and save the results in the variable "results"
results_missing <- gwqs(y~ wqs, mix_name = Xs, data = df_incomplete_drop, 
                q = 10, validation = 0.6, b = 2, b1_pos = F, 
                b1_constr = FALSE, family = "gaussian", seed = 2016)
# bar plot
gwqs_barplot(results_missing)
# scatter plot y vs wqs
gwqs_scatterplot(results_missing)
# scatter plot residuals vs fitted values
gwqs_fitted_vs_resid(results_missing)
```


## Imputing Missing Values

```{r}
#BKMR function
run_BKMR <- function(df){
  
y <- df$y
Z <- df[,2:11]

set.seed(111)

#varsel = T: perform variable selection
fitkm_missing <- kmbayes(y = y, Z = Z, iter = 10000, verbose = FALSE, varsel = TRUE)

#Estimated posterior inclusion probabilities
out <- ExtractPIPs(fitkm_missing) %>% arrange(-PIP)

return(out)
}

#WQS function
run_WQS <- function(df){
  set.seed(111)
  # we run the model and save the results in the variable "results"
  results <- gwqs(y~ wqs, mix_name = Xs, data = df, 
                q = 10, validation = 0.6, b = 2, b1_pos = F, 
                b1_constr = FALSE, family = "gaussian", seed = 2016)
  # bar plot
  gwqs_barplot(results)
  # scatter plot y vs wqs
  gwqs_scatterplot(results)
  # scatter plot residuals vs fitted values
  gwqs_fitted_vs_resid(results)
}

```



### Amelia

```{r}
set.seed(500)
imputed_amelia <- amelia(df_incomplete, m = 5)
```


### mice
```{r}
imputed_mice <- mice(df_incomplete, m=5, maxit = 50, method = 'pmm', seed = 500, printFlag=F)

run_BKMR(complete(imputed_mice))
run_WQS(complete(imputed_mice))
```

### missMDA (SVD)

```{r}
imputed_svd <- imputePCA(df_incomplete, seed=500)

run_BKMR(as.data.frame(imputed_svd$completeObs))
run_WQS(as.data.frame(imputed_svd$completeObs))
```

### missForest

```{r}
set.seed(500)
imputed_rf <- missForest(df_incomplete, variablewise = TRUE)

run_BKMR(imputed_rf$ximp)
run_WQS(imputed_rf$ximp)
```

### missRanger

```{r}
set.seed(500)
imputed_mr <- missRanger(df_incomplete, num.trees = 100, verbose = 0)

run_BKMR(imputed_mr)
run_WQS(imputed_mr)
```

### VIM

#### hot-deck

```{r}
set.seed(500)
imputed_hotdeck <- hotdeck(df_incomplete)

run_BKMR(imputed_hotdeck[,1:11])
run_WQS(imputed_hotdeck[,1:11])
```

#### irmi

```{r}
set.seed(500)
imputed_irmi <- irmi(df_incomplete)

run_BKMR(imputed_irmi[,1:11])
run_WQS(imputed_irmi[,1:11])
```


#### knn

```{r}
set.seed(500)
imputed_knn <- kNN(df_incomplete)

run_BKMR(imputed_knn[,1:11])
run_WQS(imputed_knn[,1:11])
```

### softImpute

```{r}
#using svd
set.seed(500)
imputed_si_svd <- softImpute(df_incomplete,trace=F,type="svd")

imputed_si_svd_df <- complete(df_incomplete, imputed_si_svd)

run_BKMR(imputed_si_svd_df)
run_WQS(imputed_si_svd_df)
```







