---
title: "WQS and BKMR Tutorials"
author: "Megan Grieco"
date: "2023-05-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## WQS

```{r}
library(gWQS)
library(ggplot2)
library(plotROC)
library(tictoc)
```

```{r}
# we save the names of the mixture variables in the variable "PCBs"
PCBs <- names(wqs_data)[1:34]
# we run the model and save the results in the variable "results"
results <- gwqs(yLBX ~ wqs, mix_name = PCBs, data = wqs_data, 
                q = 10, validation = 0.6, b = 2, b1_pos = TRUE, 
                b1_constr = FALSE, family = "gaussian", seed = 2016)
# bar plot
gwqs_barplot(results)
# scatter plot y vs wqs
gwqs_scatterplot(results)
# scatter plot residuals vs fitted values
gwqs_fitted_vs_resid(results)

```

```{r}
summary(results)
head(results$final_weights)

mf_df <- as.data.frame(signif(coef(summary(results$fit)), 3))
```
```{r}
results2 <- gwqs(ybin ~ wqs + sex, mix_name = PCBs,
                  data = wqs_data, q = NULL, validation = 0.4, b = 2,
                  b1_pos = TRUE, b1_constr = FALSE, family = binomial,
                  seed = 2018, plots = TRUE, tables = TRUE, pred = 0.3)

# bar plot
gwqs_barplot(results2)
# scatter plot y vs wqs
gwqs_scatterplot(results2)
```


#BKMR

## Component-wise with WQS data

```{r}
library(bkmr)
library(bkmrhat)
library(coda)
```


```{r}
y <- wqs_data$ybin
X <- ifelse(wqs_data$sex == "M",1,0) #make into numeric matrix of covariates
Z <- wqs_data[,1:34]
head(cbind(y,Z,X))
```

```{r}
#fit BKMR
set.seed(111)

#varsel = T: perform variable selection
tictoc::tic()
fitkm <- kmbayes(y = y, Z = Z, X = X, iter = 10000, verbose = FALSE, varsel = TRUE)
tictoc::toc()
#takes approx 14 minutes to run
```

```{r}
#Investigate model convergence
TracePlot(fit = fitkm, par = "beta")
TracePlot(fit = fitkm, par = "sigsq.eps")
TracePlot(fit = fitkm, par = "r", comp = 1)
```

```{r}
library(tidyverse)
#Estimated posterior inclusion probabilities
ExtractPIPs(fitkm) %>% arrange(-PIP)

#top 3 match WQS results
```

```{r}
#### Estimating h at median values of exposure
## Method 1: approximate
## Method 2: exact (mean and variance)
## Method 3: exact (full distribution)

med_vals <- apply(Z, 2, median)
Znew <- matrix(med_vals, nrow = 1)

h_est1 <- ComputePostmeanHnew(fitkm, Znew = Znew, method = "approx")
h_est2 <- ComputePostmeanHnew(fitkm, Znew = Znew, method = "exact")
set.seed(111)
samps3 <- SamplePred(fitkm, Znew = Znew, Xnew = cbind(0))

h_est_compare <- data.frame(
  method = c(1:3),
  post_mean = c(h_est1$postmean, h_est2$postmean, mean(samps3)),
  post_sd = c(sqrt(h_est1$postvar), sqrt(h_est2$postvar), sd(samps3))
)
h_est_compare
```

```{r}
#### Summarize model output

# Plot the predictor-response function
pred.resp.univar <- PredictorResponseUnivar(fit = fitkm)

library(ggplot2)
ggplot(pred.resp.univar, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + 
    geom_smooth(stat = "identity") + 
    facet_wrap(~ variable) +
  ylab("h(z)")
```

```{r}
#overall risk profile - compare changed exposure levels to median values
tictoc::tic()
risks.overall <- OverallRiskSummaries(fit = fitkm, y = y, Z = Z, X = X, 
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
tictoc::toc() #5 min to run

risks.overall

ggplot(risks.overall, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange()
```

```{r}
#single risk profiles - change from 25th to 75th for individual exposures when other exposures are held fixed (3 different levels)
tictoc::tic()
risks.singvar <- SingVarRiskSummaries(fit = fitkm, y = y, Z = Z, X = X, 
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.25, 0.50, 0.75),
                                      method = "exact")
tictoc::toc() #48 min to run
risks.singvar

ggplot(risks.singvar, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd, col = q.fixed)) + 
    geom_pointrange(position = position_dodge(width = 0.75)) + 
  coord_flip()
```

```{r}
#compare single risk profiles at 75th to 25th (IQR change)
tictoc::tic()
risks.int <- SingVarIntSummaries(fit = fitkm, y = y, Z = Z, X = X, 
                                 qs.diff = c(0.25, 0.75), 
                                 qs.fixed = c(0.25, 0.75),
                                 method = "exact")
tictoc::toc() #16 minutes
risks.int
```

## Repeat with top 3 exposures

```{r}
y <- wqs_data$ybin
X <- ifelse(wqs_data$sex == "M",1,0) #make into numeric matrix of covariates
Z <- wqs_data %>% select(LBX138LA,LBXD02LA,LBXF07LA)
head(cbind(y,Z,X))
```

```{r}
#fit BKMR
set.seed(111)

#varsel = T: perform variable selection
tictoc::tic()
fitkm <- kmbayes(y = y, Z = Z, X = X, iter = 10000, verbose = FALSE, varsel = TRUE)
tictoc::toc()
#takes 12 minutes to run
```

```{r}
#### Summarize model output

# Plot the predictor-response function
pred.resp.univar <- PredictorResponseUnivar(fit = fitkm)

library(ggplot2)
ggplot(pred.resp.univar, aes(z, est, ymin = est - 1.96*se, ymax = est + 1.96*se)) + 
    geom_smooth(stat = "identity") + 
    facet_wrap(~ variable) +
  ylab("h(z)")
```

```{r}
#overall risk profile - compare changed exposure levels to median values
tictoc::toc()
risks.overall <- OverallRiskSummaries(fit = fitkm, y = y, Z = Z, X = X, 
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
tictoc::toc()
# 5 min to run

risks.overall

ggplot(risks.overall, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange()
```

```{r}
#single risk profiles - change from 25th to 75th for individual exposures when other exposures are held fixed (3 different levels)

tictoc::tic()
risks.singvar <- SingVarRiskSummaries(fit = fitkm, y = y, Z = Z, X = X, 
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.25, 0.50, 0.75),
                                      method = "exact")
tictoc::toc() #4 min to run
risks.singvar

ggplot(risks.singvar, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd, col = q.fixed)) + 
    geom_pointrange(position = position_dodge(width = 0.75)) + 
  coord_flip()
```

```{r}
#compare single risk profiles at 75th to 25th (IQR change)
tictoc::tic()
risks.int <- SingVarIntSummaries(fit = fitkm, y = y, Z = Z, X = X, 
                                 qs.diff = c(0.25, 0.75), 
                                 qs.fixed = c(0.25, 0.75),
                                 method = "exact")
tictoc::toc() # 1 min
risks.int
```
## Reduce number of observations

```{r}
y <- wqs_data$ybin[1:100]
X <- ifelse(wqs_data$sex == "M",1,0)[1:100] #make into numeric matrix of covariates
Z <- wqs_data[1:100,1:34]
head(cbind(y,Z,X))
```

```{r}
#fit BKMR
set.seed(111)

#varsel = T: perform variable selection
tictoc::tic()
fitkm <- kmbayes(y = y, Z = Z, X = X, iter = 10000, verbose = FALSE, varsel = TRUE)
tictoc::toc()
#takes 30 sec to run
```

```{r}
#overall risk profile - compare changed exposure levels to median values
tictoc::tic()
risks.overall <- OverallRiskSummaries(fit = fitkm, y = y, Z = Z, X = X, 
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
tictoc::toc()
# 30 sec to run

risks.overall

ggplot(risks.overall, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange()
```
```{r}
#single risk profiles - change from 25th to 75th for individual exposures when other exposures are held fixed (3 different levels)

tictoc::tic()
risks.singvar <- SingVarRiskSummaries(fit = fitkm, y = y, Z = Z, X = X, 
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.25, 0.50, 0.75),
                                      method = "exact")
tictoc::toc() #4 min to run
risks.singvar

ggplot(risks.singvar, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd, col = q.fixed)) + 
    geom_pointrange(position = position_dodge(width = 0.75)) + 
  coord_flip()
```
```{r}
#compare single risk profiles at 75th to 25th (IQR change)
tictoc::tic()
risks.int <- SingVarIntSummaries(fit = fitkm, y = y, Z = Z, X = X, 
                                 qs.diff = c(0.25, 0.75), 
                                 qs.fixed = c(0.25, 0.75),
                                 method = "exact")
tictoc::toc() # 1 min
risks.int
```

## Hierarchical

```{r}
y <- wqs_data$ybin
X <- ifelse(wqs_data$sex == "M",1,0) #make into numeric matrix of covariates
Z <- wqs_data %>% select(LBX138LA,LBXD02LA,LBXF07LA)
head(cbind(y,Z,X))
```

```{r}
#correlations
round(cor(Z), 2)
```

```{r}
tictoc::tic()
fitkm_hier <- kmbayes(y = y, Z = Z, X = X, iter = 10000, varsel = TRUE, 
                      groups = c(1,2,1), verbose = FALSE)
tictoc::toc() #16 min

ExtractPIPs(fitkm_hier)
```

```{r}
#overall risk profile - compare changed exposure levels to median values
tictoc::tic()
risks.overall <- OverallRiskSummaries(fit = fitkm_hier, y = y, Z = Z, X = X, 
                                      qs = seq(0.25, 0.75, by = 0.05), 
                                      q.fixed = 0.5, method = "exact")
tictoc::toc()
# 4 min to run

risks.overall

ggplot(risks.overall, aes(quantile, est, ymin = est - 1.96*sd, ymax = est + 1.96*sd)) + 
    geom_pointrange()
```
```{r}
#single risk profiles - change from 25th to 75th for individual exposures when other exposures are held fixed (3 different levels)

tictoc::tic()
risks.singvar <- SingVarRiskSummaries(fit = fitkm_hier, y = y, Z = Z, X = X, 
                                      qs.diff = c(0.25, 0.75), 
                                      q.fixed = c(0.25, 0.50, 0.75),
                                      method = "exact")
tictoc::toc() #3 min to run
risks.singvar

ggplot(risks.singvar, aes(variable, est, ymin = est - 1.96*sd, 
                          ymax = est + 1.96*sd, col = q.fixed)) + 
    geom_pointrange(position = position_dodge(width = 0.75)) + 
  coord_flip()
```
```{r}
#compare single risk profiles at 75th to 25th (IQR change)
tictoc::tic()
risks.int <- SingVarIntSummaries(fit = fitkm_hier, y = y, Z = Z, X = X, 
                                 qs.diff = c(0.25, 0.75), 
                                 qs.fixed = c(0.25, 0.75),
                                 method = "exact")
tictoc::toc() # 1 min
risks.int
```


## Tune hyperparameters

```{r}
y <- wqs_data$ybin
X <- ifelse(wqs_data$sex == "M",1,0) #make into numeric matrix of covariates
Z <- wqs_data[,1:34]
```


```{r}
priorfits <- InvestigatePrior(y = y, Z = Z, X = X, 
                              q.seq = c(2, 1/2, 1/4, 1/16))
```

```{r}
PlotPriorFits(y = y, Z = Z, X = X, 
              fits = priorfits)
```



## Standard walkthrough

```{r}
set.seed(111)
dat <- bkmr::SimData(n = 50, M = 5, ind=1:3, Zgen="realistic")
y <- dat$y
Z <- dat$Z
X <- cbind(dat$X, rnorm(50))
head(cbind(y,Z,X))
```

```{r}
# enable parallel processing (up to 4 simultaneous processes here)
future::plan(strategy = future::multisession)

# single run of 4000 observations from bkmr package
set.seed(111)
kmfit <- suppressMessages(kmbayes(y = y, Z = Z, X = X, iter = 4000, verbose = FALSE, varsel = FALSE))

# Using rstan functions (set burnin/warmup to zero for comparability with coda numbers given later
#  posterior summaries should be performed after excluding warmup/burnin)
singlediag = kmbayes_diagnose(kmfit, warmup=0, digits_summary=2)
```